# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Breakfast' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'SwiftyJSON'
	pod 'Alamofire', '~> 4.4'
        pod 'HandyJSON', '~> 1.7.1'
        pod "TabPageViewController"
  # Pods for Breakfast

end
